import React, { useState, useEffect, useCallback } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { Copy, Check, Save, Loader2, Mail, ChevronDown, AlertCircle, Sparkles } from 'lucide-react';
import { supabase } from '../../lib/supabase';
import type { Lead } from '../../lib/supabase';
import { triggerEmail } from '../lib/openClaw';
import { useToast } from '../components/ui/Toast';

const H = 'JetBrains Mono, monospace';
const BD = 'Inter, sans-serif';
const MN = 'JetBrains Mono, monospace';

const TONES = ['Professional', 'Friendly', 'Direct', 'Consultative', 'Bold'];
const CTAS = ['Book a Call', 'Request a Demo', 'Get a Free Audit', 'See a Case Study', 'Start Free Trial'];

const fallbackEmail = (lead: Lead, tone: string, cta: string) => {
    const greeting = tone === 'Bold' ? `${lead.name} —` : `Hi ${lead.name},`;
    const opener =
        tone === 'Professional' ? `I came across ${lead.company ?? 'your company'} and wanted to reach out directly.` :
            tone === 'Friendly' ? `Hope you're having a great week! I've been following ${lead.company ?? 'your work'} and had to reach out.` :
                tone === 'Direct' ? `I'll keep this brief — we help companies like ${lead.company ?? 'yours'} close more deals faster.` :
                    tone === 'Consultative' ? `After reviewing ${lead.company ?? 'your business'}, I spotted a few opportunities worth discussing.` :
        /* Bold */                 `${lead.company ?? 'Your company'} is leaving money on the table. We can help.`;
    const body = `${lead.notes ?? 'We specialise in transforming outreach into predictable revenue.'}`;
    const ctaLine =
        cta === 'Book a Call' ? `Would you have 20 minutes this week for a quick call?` :
            cta === 'Request a Demo' ? `I'd love to show you exactly how this works — can I send over a demo?` :
                cta === 'Get a Free Audit' ? `I'll do a free audit of your current pipeline and share the findings. Interested?` :
                    cta === 'See a Case Study' ? `I'll send over a relevant case study to give you context. Fair?` :
        /* Start Free Trial */       `You can trial it completely free — no card required. Want access?`;
    return `${greeting}\n\n${opener}\n\n${body}\n\n${ctaLine}\n\nBest,\nJasper`;
};

export const EmailGen: React.FC = () => {
    const toast = useToast();
    const [leads, setLeads] = useState<Lead[]>([]);
    const [leadsLoading, setLeadsLoading] = useState(true);
    const [leadsError, setLeadsError] = useState('');
    const [selectedId, setSelectedId] = useState('');
    const [tone, setTone] = useState(TONES[0]);
    const [cta, setCta] = useState(CTAS[0]);
    const [email, setEmail] = useState('');
    const [generating, setGenerating] = useState(false);
    const [copied, setCopied] = useState(false);
    const [saved, setSaved] = useState(false);
    const [savingEmail, setSavingEmail] = useState(false);
    const [agentStatus, setAgentStatus] = useState<'idle' | 'queued' | 'error'>('idle');

    const fetchLeads = useCallback(async () => {
        setLeadsLoading(true); setLeadsError('');
        const { data, error } = await supabase.from('leads').select('id, name, company, value, status, notes').order('created_at', { ascending: false });
        setLeadsLoading(false);
        if (error) { setLeadsError(error.message); return; }
        const list = data ?? [];
        setLeads(list);
        if (list.length > 0) setSelectedId(list[0].id);
    }, []);

    useEffect(() => { fetchLeads(); }, [fetchLeads]);

    // ─── Realtime: new email saved by agent ─────────────────────────────────
    useEffect(() => {
        const ch = supabase
            .channel('emails_rt')
            .on('postgres_changes', { event: 'INSERT', schema: 'public', table: 'emails' }, () => {
                toast.success('Email ready!');
            })
            .subscribe();
        return () => { supabase.removeChannel(ch); };
        // eslint-disable-next-line react-hooks/exhaustive-deps
    }, []);

    const lead = leads.find(l => l.id === selectedId) ?? null;

    const handleGenerate = async () => {
        if (!lead) return;

        setGenerating(true); setEmail(''); setAgentStatus('idle');
        try {
            const data = await triggerEmail({ leadId: lead.id, tone, cta });
            // triggerEmail returns AgentResponse { status, message }
            // Our previous code expected { email: string } but triggerEmail's runAgent returns the raw JSON if status is ok.
            // Wait, openClaw.ts runAgent returns (await res.json()) as AgentResponse.
            // AgentResponse is { status: 'queued' | 'error', message?: string }.
            // But if the agent returns the email immediately, we need to handle it.
            // Let's look at openClaw.ts again.
            if ((data as any).email) {
                setEmail((data as any).email);
                toast.success('Email generated by agent!');
            } else {
                setAgentStatus('queued');
                toast.warning('Agent is working on the email...');
            }
        } catch (err) {
            console.error('Email gen fail:', err);
            setAgentStatus('error');
            toast.error('Agent failed to generate email.');
        }
        setGenerating(false);
    };

    const handleCopy = () => {
        navigator.clipboard.writeText(email);
        setCopied(true);
        setTimeout(() => setCopied(false), 2200);
    };

    const handleSave = async () => {
        if (!email || !lead) return;
        setSavingEmail(true);
        await supabase.from('emails').insert([{ lead_id: selectedId, tone, cta, body: email }]);
        setSavingEmail(false);
        setSaved(true);
        toast.success('Email ready!');
        setTimeout(() => setSaved(false), 2200);
    };

    const selectSt: React.CSSProperties = {
        width: '100%', padding: '10px 14px', borderRadius: 12,
        background: 'linear-gradient(145deg,#13151A,#181B21)',
        border: '1px solid rgba(255,255,255,0.07)',
        color: 'var(--text-primary,#E2E4E9)', fontFamily: BD, fontSize: 13,
        outline: 'none', cursor: 'pointer', appearance: 'none'
    };

    return (
        <div style={{ display: 'flex', flexDirection: 'column', gap: 28 }}>
            <style>{`@keyframes spin { from { transform: rotate(0deg); } to { transform: rotate(360deg); } }`}</style>

            {/* Header */}
            <div>
                <p style={{ fontFamily: MN, fontSize: 9, letterSpacing: '0.3em', color: '#7A7F8A', textTransform: 'uppercase', marginBottom: 10 }}>// Outreach · Email</p>
                <h1 style={{ fontFamily: H, fontSize: 'clamp(28px,4vw,40px)', fontWeight: 800, color: 'var(--text-primary,#FFF)', letterSpacing: '-0.5px', textTransform: 'uppercase', lineHeight: 1 }}>Email Generator</h1>
                <p style={{ fontFamily: BD, fontSize: 14, color: '#7A7F8A', marginTop: 8 }}>
                    Personalised outreach, powered by your lead data.
                </p>
            </div>

            {leadsError && (
                <div style={{ display: 'flex', alignItems: 'center', gap: 10, padding: '12px 18px', borderRadius: 12, background: 'rgba(217,91,22,0.08)', border: '1px solid rgba(217,91,22,0.3)' }}>
                    <AlertCircle size={14} style={{ color: '#D95B16' }} />
                    <span style={{ fontFamily: BD, fontSize: 13, color: '#D95B16' }}>Leads error: {leadsError}</span>
                    <button onClick={fetchLeads} style={{ marginLeft: 'auto', fontFamily: H, fontSize: 9, color: '#FF7A29', background: 'none', border: 'none', cursor: 'pointer', letterSpacing: '0.1em' }}>RETRY</button>
                </div>
            )}

            <div style={{ display: 'grid', gridTemplateColumns: 'minmax(260px, 320px) 1fr', gap: 24, alignItems: 'start', flexWrap: 'wrap' }}>

                {/* Config panel */}
                <div style={{ borderRadius: 20, background: 'linear-gradient(145deg,#14161A,#1A1C20)', border: '1px solid rgba(255,255,255,0.06)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04)', overflow: 'hidden' }}>
                    <div style={{ height: 2, background: 'linear-gradient(90deg,transparent,rgba(255,122,41,0.5),transparent)' }} />
                    <div style={{ padding: '24px 22px', display: 'flex', flexDirection: 'column', gap: 24 }}>
                        <p style={{ fontFamily: H, fontSize: 10, fontWeight: 700, letterSpacing: '0.18em', color: '#E2E4E9', textTransform: 'uppercase' }}>Configure</p>

                        <div style={{ display: 'flex', flexDirection: 'column', gap: 18 }}>
                            {/* Lead select */}
                            <div>
                                <label style={{ fontFamily: MN, fontSize: 8, letterSpacing: '0.22em', color: '#7A7F8A', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>Select Lead</label>
                                {leadsLoading ? (
                                    <div style={{ display: 'flex', alignItems: 'center', gap: 8, padding: '11px 14px', borderRadius: 12, background: 'rgba(255,255,255,0.03)', border: '1px solid rgba(255,255,255,0.07)' }}>
                                        <Loader2 size={12} style={{ color: '#4A4F5A', animation: 'spin 0.8s linear infinite' }} />
                                        <span style={{ fontFamily: BD, fontSize: 13, color: '#4A4F5A' }}>Loading leads…</span>
                                    </div>
                                ) : leads.length === 0 ? (
                                    <div style={{ padding: '11px 14px', borderRadius: 12, background: 'rgba(255,255,255,0.02)', border: '1px solid rgba(255,255,255,0.05)' }}>
                                        <span style={{ fontFamily: BD, fontSize: 12, color: '#4A4F5A' }}>No leads yet. Add one from the Leads page.</span>
                                    </div>
                                ) : (
                                    <div style={{ position: 'relative' }}>
                                        <select value={selectedId} onChange={e => setSelectedId(e.target.value)} style={{ ...selectSt, boxSizing: 'border-box' }}>
                                            {leads.map(l => (
                                                <option key={l.id} value={l.id} style={{ background: '#1A1C20', color: '#E2E4E9' }}>{l.name} — {l.company ?? 'Unknown'}</option>
                                            ))}
                                        </select>
                                        <ChevronDown size={13} style={{ position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', color: '#4A4F5A', pointerEvents: 'none' }} />
                                    </div>
                                )}
                            </div>

                            {/* Lead preview */}
                            <AnimatePresence mode="wait">
                                {lead && (
                                    <motion.div key={lead.id} initial={{ opacity: 0, height: 0, marginTop: -8 }} animate={{ opacity: 1, height: 'auto', marginTop: 4 }} exit={{ opacity: 0, height: 0, marginTop: -8 }}
                                        style={{ overflow: 'hidden' }}>
                                        <div style={{ padding: '14px', borderRadius: 12, background: 'rgba(255,122,41,0.04)', border: '1px solid rgba(255,122,41,0.12)', backgroundClip: 'padding-box' }}>
                                            <div style={{ display: 'flex', justifyContent: 'space-between', marginBottom: 4 }}>
                                                <span style={{ fontFamily: BD, fontSize: 12, fontWeight: 600, color: '#FF7A29' }}>{lead.name}</span>
                                                <span style={{ fontFamily: H, fontSize: 10, fontWeight: 700, color: '#4BE77F' }}>{lead.value ?? ''}</span>
                                            </div>
                                            <p style={{ fontFamily: BD, fontSize: 11, color: '#7A7F8A' }}>{lead.company ?? 'Independent'}</p>
                                            {lead.notes && <p style={{ fontFamily: BD, fontSize: 11, color: '#4A4F5A', marginTop: 8, lineHeight: 1.6, borderTop: '1px solid rgba(255,255,255,0.05)', paddingTop: 10 }}>{lead.notes.slice(0, 100)}{lead.notes.length > 100 ? '…' : ''}</p>}
                                        </div>
                                    </motion.div>
                                )}
                            </AnimatePresence>

                            {/* Tone */}
                            <div>
                                <label style={{ fontFamily: MN, fontSize: 8, letterSpacing: '0.22em', color: '#7A7F8A', textTransform: 'uppercase', display: 'block', marginBottom: 10 }}>Tone</label>
                                <div style={{ display: 'flex', flexWrap: 'wrap', gap: 8 }}>
                                    {TONES.map(t => (
                                        <button key={t} onClick={() => setTone(t)}
                                            style={{ padding: '8px 14px', borderRadius: 9, fontFamily: BD, fontSize: 12, cursor: 'pointer', transition: 'all 0.2s', background: tone === t ? 'rgba(255,122,41,0.15)' : 'rgba(255,255,255,0.03)', border: `1px solid ${tone === t ? 'rgba(255,122,41,0.5)' : 'rgba(255,255,255,0.07)'}`, color: tone === t ? '#FF7A29' : '#7A7F8A', fontWeight: tone === t ? 600 : 400 }}>
                                            {t}
                                        </button>
                                    ))}
                                </div>
                            </div>

                            {/* CTA */}
                            <div>
                                <label style={{ fontFamily: MN, fontSize: 8, letterSpacing: '0.22em', color: '#7A7F8A', textTransform: 'uppercase', display: 'block', marginBottom: 8 }}>Call to Action</label>
                                <div style={{ position: 'relative' }}>
                                    <select value={cta} onChange={e => setCta(e.target.value)} style={{ ...selectSt, boxSizing: 'border-box' }}>
                                        {CTAS.map(c => <option key={c} style={{ background: '#1A1C20', color: '#E2E4E9' }}>{c}</option>)}
                                    </select>
                                    <ChevronDown size={13} style={{ position: 'absolute', right: 12, top: '50%', transform: 'translateY(-50%)', color: '#4A4F5A', pointerEvents: 'none' }} />
                                </div>
                            </div>

                            {/* Generate button */}
                            <motion.button whileHover={{ scale: 1.01, boxShadow: '0 0 24px rgba(255,122,41,0.25)' }} whileTap={{ scale: 0.98 }}
                                onClick={handleGenerate} disabled={generating || !lead}
                                style={{ marginTop: 8, padding: '14px', borderRadius: 12, background: 'linear-gradient(145deg,#1E2024,#151719)', border: '1px solid rgba(255,122,41,0.5)', color: generating || !lead ? '#4A4F5A' : '#FF7A29', fontFamily: H, fontSize: 10, fontWeight: 700, letterSpacing: '0.14em', cursor: generating || !lead ? 'default' : 'pointer', boxShadow: '0 0 14px rgba(0,0,0,0.2)', display: 'flex', alignItems: 'center', justifyContent: 'center', gap: 10 }}>
                                {generating ? <><Loader2 size={13} style={{ animation: 'spin 1s linear infinite' }} />GENERATING…</> : <><Sparkles size={13} />GENERATE EMAIL</>}
                            </motion.button>

                            {/* Agent status */}
                            {agentStatus !== 'idle' && (
                                <div style={{ display: 'flex', alignItems: 'center', gap: 7, padding: '10px 14px', borderRadius: 10, background: agentStatus === 'queued' ? 'rgba(75,231,127,0.06)' : 'rgba(217,91,22,0.06)', border: `1px solid ${agentStatus === 'queued' ? 'rgba(75,231,127,0.2)' : 'rgba(217,91,22,0.2)'}` }}>
                                    <div style={{ width: 6, height: 6, borderRadius: '50%', background: agentStatus === 'queued' ? '#4BE77F' : '#D95B16', boxShadow: agentStatus === 'queued' ? '0 0 8px #4BE77F' : 'none' }} />
                                    <span style={{ fontFamily: MN, fontSize: 8, letterSpacing: '0.14em', color: agentStatus === 'queued' ? '#4BE77F' : '#D95B16' }}>
                                        {agentStatus === 'queued' ? 'OPENCLAW SYSTEM · QUEUED' : 'OPENCLAW SYSTEM · OFFLINE'}
                                    </span>
                                </div>
                            )}
                        </div>
                    </div>
                </div>

                {/* Email output */}
                <div style={{ borderRadius: 20, background: 'linear-gradient(145deg,#14161A,#1A1C20)', border: '1px solid rgba(255,255,255,0.06)', boxShadow: 'inset 0 1px 0 rgba(255,255,255,0.04)', overflow: 'hidden', display: 'flex', flexDirection: 'column' }}>
                    <div style={{ height: 2, background: 'linear-gradient(90deg,transparent,rgba(255,122,41,0.5),transparent)' }} />
                    <div style={{ padding: '18px 22px', borderBottom: '1px solid rgba(255,255,255,0.05)', display: 'flex', alignItems: 'center', justifyContent: 'space-between' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: 10 }}>
                            <Mail size={14} style={{ color: '#FF7A29' }} />
                            <p style={{ fontFamily: H, fontSize: 10, fontWeight: 700, letterSpacing: '0.18em', color: '#E2E4E9', textTransform: 'uppercase' }}>Generated Email</p>
                        </div>
                        {email && (
                            <div style={{ display: 'flex', gap: 8 }}>
                                <motion.button whileTap={{ scale: 0.95 }} onClick={handleCopy}
                                    style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 9, background: 'rgba(255,255,255,0.04)', border: '1px solid rgba(255,255,255,0.08)', color: copied ? '#4BE77F' : '#9A9FA8', fontFamily: H, fontSize: 9, fontWeight: 700, letterSpacing: '0.12em', cursor: 'pointer', transition: 'color 0.2s' }}>
                                    {copied ? <Check size={11} /> : <Copy size={11} />}
                                    {copied ? 'COPIED' : 'COPY'}
                                </motion.button>
                                <motion.button whileTap={{ scale: 0.95 }} onClick={handleSave} disabled={savingEmail}
                                    style={{ display: 'flex', alignItems: 'center', gap: 6, padding: '7px 14px', borderRadius: 9, background: saved ? 'rgba(75,231,127,0.08)' : 'rgba(255,255,255,0.04)', border: `1px solid ${saved ? 'rgba(75,231,127,0.3)' : 'rgba(255,255,255,0.08)'}`, color: saved ? '#4BE77F' : '#9A9FA8', fontFamily: H, fontSize: 9, fontWeight: 700, letterSpacing: '0.12em', cursor: savingEmail ? 'default' : 'pointer', transition: 'all 0.2s' }}>
                                    {savingEmail ? <Loader2 size={11} style={{ animation: 'spin 0.8s linear infinite' }} /> : <Save size={11} />}
                                    {saved ? 'SAVED' : 'SAVE'}
                                </motion.button>
                            </div>
                        )}
                    </div>

                    <div style={{ padding: '24px', flex: 1, minHeight: 340 }}>
                        {generating ? (
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 14, minHeight: 280 }}>
                                <Loader2 size={24} style={{ color: '#FF7A29', animation: 'spin 1s linear infinite' }} />
                                <p style={{ fontFamily: BD, fontSize: 13, color: '#4A4F5A' }}>Crafting your email…</p>
                            </div>
                        ) : email ? (
                            <motion.pre initial={{ opacity: 0, y: 8 }} animate={{ opacity: 1, y: 0 }}
                                style={{ fontFamily: BD, fontSize: 14, color: 'var(--text-primary,#E2E4E9)', lineHeight: 1.85, whiteSpace: 'pre-wrap', wordBreak: 'break-word', margin: 0 }}>
                                {email}
                            </motion.pre>
                        ) : (
                            <div style={{ display: 'flex', flexDirection: 'column', alignItems: 'center', justifyContent: 'center', height: '100%', gap: 14, minHeight: 280, opacity: 0.4 }}>
                                <Mail size={36} style={{ color: '#3A3F4A' }} />
                                <p style={{ fontFamily: H, fontSize: 11, color: '#3A3F4A', letterSpacing: '0.1em' }}>SELECT A LEAD AND GENERATE</p>
                            </div>
                        )}
                    </div>
                </div>
            </div>
        </div>
    );
};
